#!/usr/bin/env node

/**
 * Design Token CSS Generator
 *
 * This script reads design-tokens.json and generates:
 * - tokens.css: CSS custom properties (variables)
 * - tokens.scss: SCSS variables and maps
 *
 * Usage: node shared/generate-css.js
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read design tokens
const tokensPath = join(__dirname, 'design-tokens.json');
const tokens = JSON.parse(readFileSync(tokensPath, 'utf-8'));

/**
 * Generate CSS custom properties file
 */
function generateCSS() {
  const lines = [
    '/**',
    ' * Design Tokens - CSS Custom Properties',
    ' * Auto-generated from design-tokens.json',
    ' * DO NOT EDIT THIS FILE DIRECTLY',
    ' */',
    '',
    ':root {',
  ];

  // Colors - Purple palette
  lines.push('  /* Purple Color Palette */');
  Object.entries(tokens.colors.purple).forEach(([key, value]) => {
    lines.push(`  --color-purple-${key}: ${value};`);
  });
  lines.push('');

  // Primary colors (aliases for convenience)
  lines.push('  /* Primary Colors (aliases) */');
  lines.push(`  --color-primary: ${tokens.colors.purple['5']};`);
  lines.push(`  --color-primary-dark: ${tokens.colors.purple['7']};`);
  lines.push('');

  // Gradients
  lines.push('  /* Gradients */');
  Object.entries(tokens.gradients).forEach(([key, value]) => {
    lines.push(`  --gradient-${key}: ${value};`);
  });
  lines.push('');

  // Fonts
  lines.push('  /* Typography */');
  lines.push(`  --font-family: ${tokens.fonts.family};`);
  lines.push(`  --font-family-mono: ${tokens.fonts.familyMonospace};`);
  lines.push('');

  // Spacing
  lines.push('  /* Spacing */');
  Object.entries(tokens.spacing).forEach(([key, value]) => {
    lines.push(`  --spacing-${key}: ${value};`);
  });
  lines.push('');

  // Radius
  lines.push('  /* Border Radius */');
  Object.entries(tokens.radius).forEach(([key, value]) => {
    lines.push(`  --radius-${key}: ${value};`);
  });
  lines.push('');

  // Shadows
  lines.push('  /* Box Shadows */');
  Object.entries(tokens.shadows).forEach(([key, value]) => {
    lines.push(`  --shadow-${key}: ${value};`);
  });

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate SCSS variables and maps file
 */
function generateSCSS() {
  const lines = [
    '/**',
    ' * Design Tokens - SCSS Variables',
    ' * Auto-generated from design-tokens.json',
    ' * DO NOT EDIT THIS FILE DIRECTLY',
    ' */',
    '',
  ];

  // Colors - Individual variables
  lines.push('// Purple Color Palette');
  Object.entries(tokens.colors.purple).forEach(([key, value]) => {
    lines.push(`$color-purple-${key}: ${value};`);
  });
  lines.push('');

  // Primary color aliases
  lines.push('// Primary Colors (aliases)');
  lines.push(`$color-primary: ${tokens.colors.purple['5']};`);
  lines.push(`$color-primary-dark: ${tokens.colors.purple['7']};`);
  lines.push('');

  // Color map for Hugo partials
  lines.push('// Purple palette as SCSS map');
  lines.push('$purple-palette: (');
  Object.entries(tokens.colors.purple).forEach(([key, value], index, array) => {
    const isLast = index === array.length - 1;
    lines.push(`  "${key}": ${value}${isLast ? '' : ','}`);
  });
  lines.push(');');
  lines.push('');

  // Gradients
  lines.push('// Gradients');
  Object.entries(tokens.gradients).forEach(([key, value]) => {
    lines.push(`$gradient-${key}: ${value};`);
  });
  lines.push('');

  // Fonts
  lines.push('// Typography');
  lines.push(`$font-family: ${tokens.fonts.family};`);
  lines.push(`$font-family-mono: ${tokens.fonts.familyMonospace};`);
  lines.push('');

  // Spacing
  lines.push('// Spacing');
  Object.entries(tokens.spacing).forEach(([key, value]) => {
    lines.push(`$spacing-${key}: ${value};`);
  });
  lines.push('');

  // Spacing map
  lines.push('// Spacing as SCSS map');
  lines.push('$spacing: (');
  Object.entries(tokens.spacing).forEach(([key, value], index, array) => {
    const isLast = index === array.length - 1;
    lines.push(`  "${key}": ${value}${isLast ? '' : ','}`);
  });
  lines.push(');');
  lines.push('');

  // Radius
  lines.push('// Border Radius');
  Object.entries(tokens.radius).forEach(([key, value]) => {
    lines.push(`$radius-${key}: ${value};`);
  });
  lines.push('');

  // Radius map
  lines.push('// Radius as SCSS map');
  lines.push('$radius: (');
  Object.entries(tokens.radius).forEach(([key, value], index, array) => {
    const isLast = index === array.length - 1;
    lines.push(`  "${key}": ${value}${isLast ? '' : ','}`);
  });
  lines.push(');');
  lines.push('');

  // Shadows
  lines.push('// Box Shadows');
  Object.entries(tokens.shadows).forEach(([key, value]) => {
    lines.push(`$shadow-${key}: ${value};`);
  });
  lines.push('');

  // Shadows map
  lines.push('// Shadows as SCSS map');
  lines.push('$shadows: (');
  Object.entries(tokens.shadows).forEach(([key, value], index, array) => {
    const isLast = index === array.length - 1;
    lines.push(`  "${key}": ${value}${isLast ? '' : ','}`);
  });
  lines.push(');');
  lines.push('');

  return lines.join('\n');
}

/**
 * Main execution
 */
function main() {
  try {
    // Ensure build directory exists
    const buildDir = join(__dirname, 'build');
    mkdirSync(buildDir, { recursive: true });

    // Generate CSS
    const cssContent = generateCSS();
    const cssPath = join(buildDir, 'tokens.css');
    writeFileSync(cssPath, cssContent, 'utf-8');
    console.log('\u2705 Generated CSS: shared/build/tokens.css');

    // Generate SCSS
    const scssContent = generateSCSS();
    const scssPath = join(buildDir, 'tokens.scss');
    writeFileSync(scssPath, scssContent, 'utf-8');
    console.log('\u2705 Generated SCSS: shared/build/tokens.scss');

    console.log('\nDesign tokens successfully generated!');
    console.log('Source: shared/design-tokens.json');
    console.log('Outputs:');
    console.log('  - shared/build/tokens.css (CSS custom properties)');
    console.log('  - shared/build/tokens.scss (SCSS variables and maps)');
  } catch (error) {
    console.error('\u274C Error generating design tokens:', error.message);
    process.exit(1);
  }
}

main();
